development:
  adapter: postgresql
  encoding: unicode
  database: depot_development
  host: localhost
  username: serg
  password: 'hot3Zoot'

test:
  adapter: postgresql
  encoding: unicode
  database: depot_test
  host: localhost
  username: serg
  password: 'hot3Zoot'
